spring:
  application:
    name: TelegramNotesBot

bot:
  api-key: ${TELEGRAM_BOT_API_KEY}
  username: ${TELEGRAM_BOT_USERNAME}
  webhook-path: "/webhook"

astronomy:
  visiblePlanets:
    base-url: "https://api.visibleplanets.dev"
  nasa:
    base-url: "https://api.nasa.gov"
    api-key: ${NASA_API_KEY:DEMO_KEY}
  iss:
    base-url: "http://api.open-notify.org"

logging:
  level:
    root: info
    com.example.TelegramNotesBot: info


